### ISSUE TITLE
Error in check_gene_id (compareCluster)

### ISSUE THREAD

**Issue by philousap** [Yogu/clustercompare#7]
Hi, 
I am trying to use compareCluster to compare enrichment analysis of different RNA-seq made on Apis mellifera (Honeybee). 
however, i have got an error message 
_Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped...._

Here my explanation

gL1<- geneList with logFC and names (geneID) for Apis mellifera.
gL2<- is the same but for another geneSet for APpis Mellifera 

_**Example: 
geneID: 725165    726592    724282 113219072 107965070 107964776 100577773 100578475 
LogFC   1.190358  1.190266  1.189899  1.189409  1.188527  1.188432  1.188149  1.187474**_

When I run them as 
```
gseKEGG(geneList=gL1,organism="ame", pvalueCutoff = 0.05, pAdjustMethod = "BH")
gseKEGG(geneList=gL2,organism="ame", pvalueCutoff = 0.05, pAdjustMethod = "BH")
```

they work perfectly but I soon I switch to compareCluster I have the error: 

```
> formula_res <- compareCluster(geneClusters=gL1~gL2, data=universe_annotation, fun="gseKEGG", organism="ame",pAdjustMethod = "BH")
```

Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....

I have tried:
```
gL<-list(p1=gL1, p2=gL2)
compareCluster(geneClusters=gL, data=universe_annotation, fun="gseKEGG", organism="ame",pAdjustMethod = "BH")
```

 I have the following error message: 

Error in compareCluster(geneClusters = gL, data = universe_annotation,  : 
object 'grouping.formula' not found 

I am not sure what I am missing here. 

Thanks, 

Phiphi

**Comment by Yogu** [comment]
Hi there! I think you might be looking for the [clusterProfile repository](https://github.com/YuLab-SMU/clusterProfiler/issues).

(this repository is the code of my bachelor's thesis, which is a [visualization for differences between clusters](https://clustercompare.jan-melcher.de/))

**Comment by philousap** [comment]
Sorry, thank you @Yogu !

**Comment by philousap** [comment]
Wrong repository! Sorry !
